[caller_settings]
config_name = "dna_r9.4.1_450bps_fast_prom"
host = "ipc:///tmp/.guppy"
port = 5555
barcode_kits = ["SQK-NBD110-24"]
align_ref = "/data/refs/hg38_simple.mmi"

[conditions]
reference = "/data/refs/hg38_simple.mmi"

[barcodes.unclassified]
name = "unclassified_reads"
control = false
min_chunks = 0
max_chunks = 2
targets = []
single_on = "unblock"
multi_on = "unblock"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

[barcodes.classified]
name = "classified_reads"
control = false
min_chunks = 0
max_chunks = 2
targets = []
single_on = "unblock"
multi_on = "unblock"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

[barcodes.barcode05]
name = "barcode05_NA12878_tst-170"
control = false
min_chunks = 0
max_chunks = 2
targets = "resources/tst_170_coords_extended.csv"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

[barcodes.barcode06]
name = "barcode06_NB4_tst-fusion"
control = false
min_chunks = 0
max_chunks = 2
targets = "resources/tst_fusion_coords_extended.csv"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

[barcodes.barcode07]
name = "barcode07_22RV1_COSMIC"
control = false
min_chunks = 0
max_chunks = 2
targets = "resources/CancerPanelTargets.txt"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
