
[caller_settings.guppy]
config = "dna_r10.4.1_e8.2_400bps_fast"
address = "ipc:///tmp/.guppy/5555"
debug_log = "Rapid_CNS.fq"

[mapper_settings.mappy]
fn_idx_in = "/data/references/hg38_simple.mmi"
debug_log = "Rapid_CNS.paf"

[[regions]]
name = "Rapid_CNS"
min_chunks = 1
max_chunks = 4
targets = "resources/panel_adaptive_nogenenames_20122021_hg38.bed"
single_off = "unblock"
multi_off = "unblock"
single_on = "stop_receiving"
multi_on = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"


[[regions]]
name = "Direct_CNS"
min_chunks = 1
max_chunks = 4
targets = ["chr2,3001,4000,-", "chr2,3000,4000,-", "chr20,3000,4000,-"]
single_off = "unblock"
multi_off = "unblock"
single_on = "stop_receiving"
multi_on = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"